### ISSUE TITLE
Service must return a JSON response

### ISSUE THREAD

**Issue by GimmickNG** [NRG-UCalgary/test-service-python#4]
Currently, only "Hello, _name_" is displayed for a given JSON; it should return a JSON response instead.

**Comment by mkartik** [comment]
Hi @GimmickNG, can I take this issue?

**Comment by GimmickNG** [comment]
Sure, go for it.

**Comment by mkartik** [comment]
Can you provide a sample expected JSON response?

**Comment by GimmickNG** [comment]
Sure, for now it could be kept simple - a single field _response_ containing the result:

Input:
```
{
    "name": "test"
}
```

Output:
```
{
    "response": "Hello, test"
}
```
